AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This is my first
  template for
  using Cloudformation.
    
Resources:
  AslanInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0230bd60aa48260c6
      InstanceType: t2.micro
      KeyName: morgoliath-clarusway # Use your own keypair without .pem
      SecurityGroups: 
        - !Ref AslanSecGrp
      Tags: 
        - Key: Name
          Value: Aslan-instance

  AslanSecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows only SSH connection # Required
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0