AWSTemplateFormatVersion: 2010-09-09
Description: | 
  This is the new cloudformation template.Kittens Carousel is a static website 
  application deployed with Apache Web Server 
  on AWS Elastic Compute Cloud (EC2) Instance 
  using AWS Cloudformation Service.
  

  
Resources:
 yamaninstance:
  Type: AWS::EC2::Instance
  Properties:
    ImageId: ami-0230bd60aa48260c6

    InstanceType: t2.micro

    KeyName: firstkey
  
    SecurityGroups: 
      - !Ref newsec
  
    Tags: 
      - Key: Name 
        Value: Ymn

    UserData:




    
 newsec: 
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows only SSH connection
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

        
